# Generated by Django 3.2.6 on 2021-08-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/news')),
                ('title', models.CharField(max_length=50)),
                ('badge', models.CharField(max_length=20)),
            ],
        ),
    ]
